apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: *******************************************************************************************************************************************************************************************