apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      description: Image name including tag
      type: string
  workspaces:
    - name: source
      description: Source code workspace
    - name: docker-credentials
      description: Docker config secret workspace
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --destination=$(params.IMAGE)
        - --force
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
          readOnly: true
          
  volumes:
    - name: docker-config
      secret:
        secretName: docker-credentials
        items:
        - key: .dockerconfigjson
          path: config.json
