apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/srikxcipher/rails_app.git'
    path: kubernetes-files/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true